stages:
  - build
  - test
  - deploy
image: jagestah/resroulette:latest
Init and Plan Terraform:
  stage: build
  script:
    - ls
    - cd infra
    - terraform init
    - terraform plan -out=terraform.plan
  artifacts:
    paths:
      - infra/terraform.plan
# job 2:
#   stage: test
#   script: echo "Job 2"
# Push to Docker:
#   stage: deploy
#   when: on_success
#   only:
#     - master@Jagestah/ResRoulette
#   script: echo "This is where we push to Dockerhub"
Apply Terraform Plan:
  stage: deploy
  when: manual
  only:
    - master@Jagestah/ResRoulette
  script: terraform apply infra/terraform.plan
