stages:
  - build
  - test
  - deploy
image: jagestah/resroulette:latest
job 1:
  stage: build
  script: echo "job 1"
job 2:
  stage: test
  script: echo "Job 2"
Push to Docker:
  stage: deploy
  when: on_success
  only:
    - master@Jagestah/ResRoulette
  script: echo "This is where we push to Dockerhub"
job 3:
  stage: deploy
  when: on_success
  only:
    - master@Jagestah/ResRoulette
  script: echo "This script only runs on master branch"
