stages:
  - build
  - test
  - deploy
image: jagestah/resroulette:latest
Init and Plan Terraform:
  stage: build
  script:
    - cd infra
    - terraform init
    - terraform plan -out=terraform.plan
  artifacts:
    paths:
      - infra/terraform.plan

Apply Terraform Plan:
  stage: deploy
  when: manual
  only:
    - master@Jagestah/ResRoulette
  script:
    - cd infra
    - terraform init
    - terraform apply terraform.plan
